apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: para-pvc
  namespace: demo
  labels:
    app: para-pvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: para-relay-pvc
  namespace: demo
  labels:
    app: para-relay-pvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
