apiVersion: v1
kind: Service
metadata:
  name: para-service-clusterip
  namespace: demo
spec:
  selector:
    app: paranode
    mode: para
  type: ClusterIP
  ports:
    - name: ws
      protocol: TCP
      port: 9944
      targetPort: 9944
    - name: p2p
      protocol: TCP
      port: 30333
      targetPort: 30333
---
apiVersion: v1
kind: Service
metadata:
  name: para-headless-service
  namespace: demo
spec:
  clusterIP: None
  selector:
    app: paranode
    mode: para
  ports:
    - name: ws
      protocol: TCP
      port: 9944
      targetPort: 9944
    - name: p2p
      protocol: TCP
      port: 30333
      targetPort: 30333
