apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boot-pvc
  namespace: demo
  labels:
    app: boot-pvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
