apiVersion: v1
kind: Service
metadata:
  name: boot-service-clusterip
  namespace: demo
spec:
  selector:
    app: bootnode
  type: ClusterIP
  ports:
    - name: ws
      protocol: TCP
      port: 9944
      targetPort: 9944
    - name: p2p
      protocol: TCP
      port: 30333
      targetPort: 30333
---
apiVersion: v1
kind: Service
metadata:
  name: boot-headless-service
  namespace: demo
spec:
  clusterIP: None
  selector:
    app: bootnode
  ports:
    - name: ws
      protocol: TCP
      port: 9944
      targetPort: 9944
    - name: p2p
      protocol: TCP
      port: 30333
      targetPort: 30333
---
apiVersion: v1
kind: Service
metadata:
  name: relay-service-clusterip
  namespace: demo
spec:
  selector:
    mode: relay
  type: ClusterIP
  ports:
    - name: ws
      protocol: TCP
      port: 9944
      targetPort: 9944
    - name: p2p
      protocol: TCP
      port: 30333
      targetPort: 30333
