apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relay-pvc
  namespace: demo
  labels:
    app: relay-pvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
