apiVersion: v1
kind: Service
metadata:
  name: relay-headless-service
  namespace: demo
spec:
  clusterIP: None
  selector:
    app: relaynode
  ports:
    - name: ws
      protocol: TCP
      port: 9944
      targetPort: 9944
    - name: p2p
      protocol: TCP
      port: 30333
      targetPort: 30333
